addons:
  code_climate: 
    repo_token: 078d9b1f419fc7ca7ccd0de3d9c02843872501a5e732bcd478e9086c41a5fef2
before_script: 
- npm install -g grunt-cli bower
- bower install
node_js: 
- 0.10
after_script: 
- cat build/reports/coverage/report-lcov/lcov.info | codeclimate
language: node_js
